services:
  db:
    image: postgres:16-alpine
    container_name: mcp-pg-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  etl:
    build: .
    container_name: mcp-pg-etl
    command: ["python", "etl.py"]
    depends_on:
      db:
        condition: service_healthy
    env_file: [.env]
    volumes:
      - ./data.xlsx:/app/data.xlsx:ro

  app:
    build: .
    container_name: mcp-pg-app
    command: ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]
    depends_on:
      etl:
        condition: service_completed_successfully
    env_file: [.env]
    ports:
      - 8001:8501

volumes:
  pgdata:
